DoXuanTrang_21124055_703/DoXuanTrang_21124055_703/ViewComponents/RenderViewComponent.cs
using DoXuanTrang_21124055_703.Models;
using Microsoft.AspNetCore.Mvc;

namespace DoXuanTrang_21124055_703.ViewComponents
{
	public class RenderViewComponent : ViewComponent
	{
		private List<Category> cats = new List<Category>();
		private readonly OnlineShopContext _db;
		public RenderViewComponent(OnlineShopContext db)
		{
			_db = db;
			cats = _db.Categories.ToList();
		}
		public async Task<IViewComponentResult> InvokeAsync()
		{
			return View("RenderProductLeft", cats);
		}
	}
}

DoXuanTrang_21124055_703/DoXuanTrang_21124055_703/Views/Shared/DoXuanTrang_Footer.cshtml
<div class="footer">
	<div class="container">
		<div class="w3_footer_grids">
			<div class="col-md-3 w3_footer_grid">
				<h3>Contact</h3>
				<ul class="address">
					<li><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i><a href="mailto:info@example.com">info@example.com</a></li>
					<li><i class="glyphicon glyphicon-earphone" aria-hidden="true"></i>+1234 567 567</li>
				</ul>
			</div>
			<div class="col-md-3 w3_footer_grid">
				<h3>Information</h3>
				<ul class="info">
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="about.html">About Us</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="contact.html">Contact Us</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="short-codes.html">Short Codes</a></li>
				</ul>
			</div>
			<div class="col-md-3 w3_footer_grid">
				<h3>Category</h3>
				<ul class="info">
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="groceries.html">Groceries</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="household.html">Household</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="personalcare.html">Personal Care</a></li>
				</ul>
			</div>
			<div class="col-md-3 w3_footer_grid">
				<h3>Profile</h3>
				<ul class="info">
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="products.html">Store</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="checkout.html">My Cart</a></li>
					<li><i class="fa fa-arrow-right" aria-hidden="true"></i><a href="login.html">Login</a></li>
				</ul>
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
</div>
<div class="footer-botm">
	<div class="container">
		<div class="w3layouts-foot">
			<ul>
				<li><a href="#" class="w3_agile_facebook"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
				<li><a href="#" class="agile_twitter"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
				<li><a href="#" class="w3_agile_dribble"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
				<li><a href="#" class="w3_agile_vimeo"><i class="fa fa-vimeo" aria-hidden="true"></i></a></li>
			</ul>
		</div>
		<div class="payment-w3ls">
			<img src="images/card.png" alt=" " class="img-responsive">
		</div>
		<div class="clearfix"> </div>
	</div>
</div>

DoXuanTrang_21124055_703/DoXuanTrang_21124055_703/Views/Shared/DoXuanTrang_Header.cshtml
<div class="agileits_header">
	<div class="container">
		<div class="w3l_offers">
			<p>Đỗ Xuân Tráng - Mã sinh viên: 211240555 . <a href="products.html">Đề thi: 703</a></p>
		</div>
		<div class="agile-login">
			<ul>
				<li><a href="registered.html"> Create Account </a></li>
				<li><a href="login.html">Login</a></li>
				<li><a href="contact.html">Help</a></li>

			</ul>
		</div>
		<div class="product_list_header">
			<form action="#" method="post" class="last">
				<input type="hidden" name="cmd" value="_cart">
				<input type="hidden" name="display" value="1">
				<button class="w3view-cart" type="submit" name="submit" value=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></button>
			</form>
		</div>
		<div class="clearfix"> </div>
	</div>
</div>
<div class="logo_products">
	<div class="container">
		<div class="w3ls_logo_products_left1">
			<ul class="phone_email">
				<li><i class="fa fa-phone" aria-hidden="true"></i>Order online or call us : (+0123) 234 567</li>
			</ul>
		</div>
		<div class="w3ls_logo_products_left">
			<h1><a href="index.html">Đỗ Xuân Tráng</a></h1>
		</div>
		<div class="w3l_search">
			<input type="search" name="Search" placeholder="Search for a Product..." required="">
			<button type="submit" class="btn btn-default search" aria-label="Left Align">
				<i class="fa fa-search" aria-hidden="true"> </i>
			</button>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"> </div>
	</div>
</div>

DoXuanTrang_21124055_703/DoXuanTrang_21124055_703/Views/Shared/DoXuanTrang_Layout.cshtml
<!--
author: W3layouts
author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>Online Shopping</title>
	<!-- for-mobile-apps -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="Super Market, Online Shopping" />

	<!-- //for-mobile-apps -->
	<link href="~/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
	<link href="~/css/style.css" rel="stylesheet" type="text/css" media="all" />
	<link rel="stylesheet" type="text/css" href="~/css/jquery-ui-1.css">
	<!-- font-awesome icons -->
	<link href="~/css/font-awesome.css" rel="stylesheet">
	<!-- //font-awesome icons -->
	<!-- js -->
	<script src="~/js/jquery-1.11.1.min.js"></script>
	<!-- //js -->
</head>

<body>
	<!-- header -->
	<partial name="DoXuanTrang_Header"/>
	<!-- //header -->
	<!-- main navigation -->
	<partial name="DoXuanTrang_Nav" />
	<!-- //main navigation -->
	<!--- main content --->
	<div class="products">
		<div class="container">
			<!-- left categories -->
			@await Component.InvokeAsync("Render")
			<!-- /left categories -->
			<!-- right products grid -->
			@RenderBody()
			<div class="clearfix"> </div>
			<!-- right products grid -->
		</div>
	</div>
	<!--- main content --->
	<!-- footer -->
	<partial name="DoXuanTrang_Footer" />
	<!-- //footer -->
	@RenderSection("Scripts", required:false)
</body>
</html>

DoXuanTrang_21124055_703/DoXuanTrang_21124055_703/Views/Shared/DoXuanTrang_Main.cshtml
<div class="col-md-8 products-right">
	<div class="agile_top_brands_grids">
		<div class="col-md-4 top_brand_left">
			<div class="hover14 column">
				<div class="agile_top_brand_left_grid">
					<div class="agile_top_brand_left_grid_pos">
						<img src="images/offer.png" alt=" " class="img-responsive">
					</div>
					<div class="agile_top_brand_left_grid1">
						<figure>
							<div class="snipcart-item block">
								<div class="snipcart-thumb">
									<a href="single.html"><img title=" " alt=" " src="images/pf4.png"></a>
									<p>Sampann-toor-dal</p>
									<h4>$35.99 <span>$55.00</span></h4>
								</div>
								<div class="snipcart-details top_brand_home_details">
									<form action="#" method="post">
										<fieldset>
											<input type="hidden" name="cmd" value="_cart">
											<input type="hidden" name="add" value="1">
											<input type="hidden" name="business" value=" ">
											<input type="hidden" name="item_name" value="Fortune Sunflower Oil">
											<input type="hidden" name="amount" value="35.99">
											<input type="hidden" name="discount_amount" value="1.00">
											<input type="hidden" name="currency_code" value="USD">
											<input type="hidden" name="return" value=" ">
											<input type="hidden" name="cancel_return" value=" ">
											<input type="submit" name="submit" value="Add to cart" class="button">
										</fieldset>
									</form>
								</div>
							</div>
						</figure>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-4 top_brand_left">
			<div class="hover14 column">
				<div class="agile_top_brand_left_grid">
					<div class="agile_top_brand_left_grid_pos">
						<img src="images/offer.png" alt=" " class="img-responsive">
					</div>
					<div class="agile_top_brand_left_grid1">
						<figure>
							<div class="snipcart-item block">
								<div class="snipcart-thumb">
									<a href="single.html"><img title=" " alt=" " src="images/bv3.png"></a>
									<p>Parryss-sugar</p>
									<h4>$30.99 <span>$45.00</span></h4>
								</div>
								<div class="snipcart-details top_brand_home_details">
									<form action="#" method="post">
										<fieldset>
											<input type="hidden" name="cmd" value="_cart">
											<input type="hidden" name="add" value="1">
											<input type="hidden" name="business" value=" ">
											<input type="hidden" name="item_name" value="basmati rise">
											<input type="hidden" name="amount" value="30.99">
											<input type="hidden" name="discount_amount" value="1.00">
											<input type="hidden" name="currency_code" value="USD">
											<input type="hidden" name="return" value=" ">
											<input type="hidden" name="cancel_return" value=" ">
											<input type="submit" name="submit" value="Add to cart" class="button">
										</fieldset>
									</form>
								</div>
							</div>
						</figure>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-4 top_brand_left">
			<div class="hover14 column">
				<div class="agile_top_brand_left_grid">
					<div class="agile_top_brand_left_grid_pos">
						<img src="images/offer.png" alt=" " class="img-responsive">
					</div>
					<div class="agile_top_brand_left_grid_pos">
						<img src="images/offer.png" alt=" " class="img-responsive">
					</div>
					<div class="agile_top_brand_left_grid1">
						<figure>
							<div class="snipcart-item block">
								<div class="snipcart-thumb">
									<a href="single.html"><img src="images/16.png" alt=" " class="img-responsive"></a>
									<p>Saffola-gold</p>
									<h4>$80.99 <span>$105.00</span></h4>
								</div>
								<div class="snipcart-details top_brand_home_details">
									<form action="#" method="post">
										<fieldset>
											<input type="hidden" name="cmd" value="_cart">
											<input type="hidden" name="add" value="1">
											<input type="hidden" name="business" value=" ">
											<input type="hidden" name="item_name" value="Pepsi soft drink">
											<input type="hidden" name="amount" value="80.00">
											<input type="hidden" name="discount_amount" value="1.00">
											<input type="hidden" name="currency_code" value="USD">
											<input type="hidden" name="return" value=" ">
											<input type="hidden" name="cancel_return" value=" ">
											<input type="submit" name="submit" value="Add to cart" class="button">
										</fieldset>
									</form>
								</div>
							</div>
						</figure>
					</div>
				</div>
			</div>
		</div>
		<div class="clearfix"> </div>
	</div>
</div>

DoXuanTrang_21124055_703/DoXuanTrang_21124055_703/Views/Shared/DoXuanTrang_Nav.cshtml
<div class="navigation-agileits">
	<div class="container">
		<nav class="navbar navbar-default">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header nav_2">
				<button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
				<ul class="nav navbar-nav">
					<li class="active"><a href="#" class="act">Home</a></li>
					<!-- Mega Menu -->
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Beverages<b class="caret"></b></a>
						<ul class="dropdown-menu multi-column columns-3">
							<div class="row">
								<div class="multi-gd-img">
									<ul class="multi-column-dropdown">
										<h6>Tea & Coeffe</h6>
										<li><a href="#">Green Tea</a></li>
										<li><a href="#">Ground Coffee</a></li>
										<li><a href="#">Herbal Tea</a></li>
										<li><a href="#">Instant Coffee</a></li>
										<li><a href="#"> Tea </a></li>
										<li><a href="#">Tea Bags</a></li>
									</ul>
								</div>
							</div>
						</ul>
					</li>
					<li><a href="#">Gourmet</a></li>
					<li><a href="#">Offers</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
			</div>
		</nav>
	</div>
</div>

DoXuanTrang_21124055_703/DoXuanTrang_21124055_703/Views/Shared/DoXuanTrang_ProductLeft.cshtml
<div class="col-md-4 products-left">
	<div class="categories">
		<h2>Categories</h2>
		<ul class="cate">
			<li><a href="#"><i class="fa fa-arrow-right" aria-hidden="true"></i>Fruits And Vegetables</a></li>

			<li><a href="#"><i class="fa fa-arrow-right" aria-hidden="true"></i>Grocery & Staples</a></li>

			<li><a href="#"><i class="fa fa-arrow-right" aria-hidden="true"></i>PersonalCare</a></li>
		</ul>
	</div>
</div>

DoXuanTrang_21124055_703/DoXuanTrang_21124055_703/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DoXuanTrang_21124055_703</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DoXuanTrang_21124055_703.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DoXuanTrang_21124055_703</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DoXuanTrang_21124055_703 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>